version: "3"

services:
  app:
    image: erp
    command: uvicorn --reload --host 0.0.0.0 --port 8000 app.entrypoint.api.main:app
    ports:
      - "8000:8000"
    env_file: .env

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_pass
      POSTGRES_DB: erpwallet
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"

volumes:
    postgres:
